map $http_time_zone $is_utc8 {
    default       0;
    "UTC+8"       1;
}
server {
    listen 443 ssl;
    http2 on;
    server_name testh5buy.yzkj.com;

    # 证书和私钥文件路径
    ssl_certificate /etc/nginx/ssl/h5buy.pem;
    ssl_certificate_key /etc/nginx/ssl/h5buy.key;

    # 优化配置（可选，但推荐）
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
    ssl_prefer_server_ciphers on;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    # 开启 OCSP Stapling，提高性能
    ssl_stapling on;
    ssl_stapling_verify on;
    resolver_timeout 5s;

    gzip  on;
    gzip_min_length  1k;
    gzip_buffers     4 16k;
    gzip_http_version 1.1;
    gzip_comp_level 6;
    gzip_types       text/plain application/x-javascript text/css application/xml text/javascript application/x-httpd-php application/javascript application/json;
    gzip_disable "MSIE [1-6]\.";
    gzip_vary on;
    resolver 8.8.8.8;


    index index.htm index.html ;
    root /usr/share/nginx/html/h5_buy;
    error_log /var/nginx/log/error.log;
    access_log /var/nginx/log/acces.log;

    location = /pages/user/invite/personalPromotion {
    	if ($http_user_agent !~* (mobile|nokia|iphone|ipad|android|samsung|htc|blackberry)) {
 		rewrite ^(.*) https://yzkj.com/com-share redirect;
   	}
        index  index.html index.htm;
    	try_files $uri $uri/ /index.html;
    }



    location /.well-known{
        alias /home/.h5well-known;
	add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

#解决Router(mode: 'history')模式下，刷新路由地址不能找到页面的问题
    location / {
    	if ($http_user_agent !~* (mobile|nokia|iphone|ipad|android|samsung|htc|blackberry)) {
            return 301 https://yzkj.com$is_args$args;
   	}

	root /usr/share/nginx/html/h5_buy;

    	index  index.html index.htm;
    	try_files $uri $uri/ /index.html =404;
    }

    location /register {
    	return 302 https://testh5buy.yzkj.com/pages/register/index$is_args$args;
    }
    location /pages/goods/recommend {
    	if ($http_user_agent !~* (mobile|nokia|iphone|ipad|android|samsung|htc|blackberry)) {
             return  301 https://testh5buy.yzkj.com/shopWindow$is_args$args;
        }

        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }


    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
      root html;
    }
    location /aps-api {
        if ($is_utc8) {
          #return 301 https://yzkj.com/404.html;
        }
            #include cors.conf;
        port_in_redirect on;
        proxy_pass http://ip:8081/;
        proxy_redirect  off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-NginX-Proxy true;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_connect_timeout 600s;
        proxy_read_timeout 600;
        proxy_send_timeout 600s;
    }
}
